version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
    - pgdata:/var/lib/postgresql/data
  employee_list:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./employee_list:/employee_list
    command:
      - python ./manage.py makemigrations
      - python ./manage.py migrate
      - python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata: