version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
    - pgdata:/var/lib/postgresql/data
  employee_list:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./employee_list:/employee_list
    command: sh ./scripts/run_backend.sh
    restart: on-failure
    depends_on:
      - db
volumes:
  pgdata: