# Generated by Django 4.0.2 on 2022-02-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_age_employee_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profession',
            field=models.CharField(choices=[('web dev', 'web developer'), ('doc', 'doctor')], max_length=50),
        ),
    ]
