# Generated by Django 4.0.2 on 2022-02-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profession',
            field=models.CharField(choices=[('web developer', 'web developer'), ('phtographer', 'photographer'), ('data analyst', 'data analyst'), ('teacher', 'teacher')], max_length=50),
        ),
    ]
