# Generated by Django 4.0.2 on 2022-02-10 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.profession'),
        ),
    ]
